/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EditorialBoardRouteImport } from './routes/editorial-board'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedFounderRouteImport } from './routes/_authenticated/founder'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as ArticlePaperlyIdRouteImport } from './routes/article.$paperlyId'
import { Route as PaperPublicIdRouteImport } from './routes/paper.$publicId'
import { Route as PoliciesIndexRouteImport } from './routes/policies.index'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as VerifyCertIdRouteImport } from './routes/verify_.$certId'
import { Route as AuthenticatedMyResearchIndexRouteImport } from './routes/_authenticated/my-research.index'
import { Route as AuthenticatedMyResearchIdRouteImport } from './routes/_authenticated/my-research.$id'
import { Route as AuthenticatedManuscriptPaperIdRouteImport } from './routes/_authenticated/manuscript.$paperId'
import { Route as AuthenticatedOrcidCallbackRouteImport } from './routes/_authenticated/orcid.callback'
import { Route as VerifyCertificateCertIdRouteImport } from './routes/verify_.certificate.$certId'
import { Route as ApiPublicPaymentsRazorpayWebhookRouteImport } from './routes/api/public/payments/razorpay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialBoardRoute = EditorialBoardRouteImport.update({
  id: '/editorial-board',
  path: '/editorial-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFounderRoute = AuthenticatedFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticlePaperlyIdRoute = ArticlePaperlyIdRouteImport.update({
  id: '/article/$paperlyId',
  path: '/article/$paperlyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperPublicIdRoute = PaperPublicIdRouteImport.update({
  id: '/paper/$publicId',
  path: '/paper/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertIdRoute = VerifyCertIdRouteImport.update({
  id: '/verify_/$certId',
  path: '/verify/$certId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyResearchIndexRoute =
  AuthenticatedMyResearchIndexRouteImport.update({
    id: '/my-research/',
    path: '/my-research/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyResearchIdRoute =
  AuthenticatedMyResearchIdRouteImport.update({
    id: '/my-research/$id',
    path: '/my-research/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManuscriptPaperIdRoute =
  AuthenticatedManuscriptPaperIdRouteImport.update({
    id: '/manuscript/$paperId',
    path: '/manuscript/$paperId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcidCallbackRoute =
  AuthenticatedOrcidCallbackRouteImport.update({
    id: '/orcid/callback',
    path: '/orcid/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const VerifyCertificateCertIdRoute = VerifyCertificateCertIdRouteImport.update({
  id: '/verify_/certificate/$certId',
  path: '/verify/certificate/$certId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsRazorpayWebhookRoute =
  ApiPublicPaymentsRazorpayWebhookRouteImport.update({
    id: '/api/public/payments/razorpay-webhook',
    path: '/api/public/payments/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/explore': typeof ExploreRoute
  '/fees': typeof FeesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/founder': typeof AuthenticatedFounderRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/article/$paperlyId': typeof ArticlePaperlyIdRoute
  '/paper/$publicId': typeof PaperPublicIdRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/policies/': typeof PoliciesIndexRoute
  '/my-research/$id': typeof AuthenticatedMyResearchIdRoute
  '/manuscript/$paperId': typeof AuthenticatedManuscriptPaperIdRoute
  '/orcid/callback': typeof AuthenticatedOrcidCallbackRoute
  '/verify/certificate/$certId': typeof VerifyCertificateCertIdRoute
  '/my-research/': typeof AuthenticatedMyResearchIndexRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/explore': typeof ExploreRoute
  '/fees': typeof FeesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/founder': typeof AuthenticatedFounderRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/article/$paperlyId': typeof ArticlePaperlyIdRoute
  '/paper/$publicId': typeof PaperPublicIdRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/policies': typeof PoliciesIndexRoute
  '/my-research/$id': typeof AuthenticatedMyResearchIdRoute
  '/manuscript/$paperId': typeof AuthenticatedManuscriptPaperIdRoute
  '/orcid/callback': typeof AuthenticatedOrcidCallbackRoute
  '/verify/certificate/$certId': typeof VerifyCertificateCertIdRoute
  '/my-research': typeof AuthenticatedMyResearchIndexRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/explore': typeof ExploreRoute
  '/fees': typeof FeesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/founder': typeof AuthenticatedFounderRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/article/$paperlyId': typeof ArticlePaperlyIdRoute
  '/paper/$publicId': typeof PaperPublicIdRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/verify_/$certId': typeof VerifyCertIdRoute
  '/policies/': typeof PoliciesIndexRoute
  '/_authenticated/my-research/$id': typeof AuthenticatedMyResearchIdRoute
  '/_authenticated/manuscript/$paperId': typeof AuthenticatedManuscriptPaperIdRoute
  '/_authenticated/orcid/callback': typeof AuthenticatedOrcidCallbackRoute
  '/verify_/certificate/$certId': typeof VerifyCertificateCertIdRoute
  '/_authenticated/my-research/': typeof AuthenticatedMyResearchIndexRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/editorial-board'
    | '/explore'
    | '/fees'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/admin'
    | '/certificates'
    | '/dashboard'
    | '/profile'
    | '/reviews'
    | '/founder'
    | '/submit'
    | '/article/$paperlyId'
    | '/paper/$publicId'
    | '/policies/$slug'
    | '/verify/$certId'
    | '/policies/'
    | '/my-research/$id'
    | '/manuscript/$paperId'
    | '/orcid/callback'
    | '/verify/certificate/$certId'
    | '/my-research/'
    | '/api/public/payments/razorpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/editorial-board'
    | '/explore'
    | '/fees'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/admin'
    | '/certificates'
    | '/dashboard'
    | '/profile'
    | '/reviews'
    | '/founder'
    | '/submit'
    | '/article/$paperlyId'
    | '/paper/$publicId'
    | '/policies/$slug'
    | '/verify/$certId'
    | '/policies'
    | '/my-research/$id'
    | '/manuscript/$paperId'
    | '/orcid/callback'
    | '/verify/certificate/$certId'
    | '/my-research'
    | '/api/public/payments/razorpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/editorial-board'
    | '/explore'
    | '/fees'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/_authenticated/admin'
    | '/_authenticated/certificates'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/reviews'
    | '/_authenticated/founder'
    | '/_authenticated/submit'
    | '/article/$paperlyId'
    | '/paper/$publicId'
    | '/policies/$slug'
    | '/verify_/$certId'
    | '/policies/'
    | '/_authenticated/my-research/$id'
    | '/_authenticated/manuscript/$paperId'
    | '/_authenticated/orcid/callback'
    | '/verify_/certificate/$certId'
    | '/_authenticated/my-research/'
    | '/api/public/payments/razorpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  EditorialBoardRoute: typeof EditorialBoardRoute
  ExploreRoute: typeof ExploreRoute
  FeesRoute: typeof FeesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  ArticlePaperlyIdRoute: typeof ArticlePaperlyIdRoute
  PaperPublicIdRoute: typeof PaperPublicIdRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  VerifyCertIdRoute: typeof VerifyCertIdRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
  VerifyCertificateCertIdRoute: typeof VerifyCertificateCertIdRoute
  ApiPublicPaymentsRazorpayWebhookRoute: typeof ApiPublicPaymentsRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-board': {
      id: '/editorial-board'
      path: '/editorial-board'
      fullPath: '/editorial-board'
      preLoaderRoute: typeof EditorialBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founder': {
      id: '/_authenticated/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof AuthenticatedFounderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/article/$paperlyId': {
      id: '/article/$paperlyId'
      path: '/article/$paperlyId'
      fullPath: '/article/$paperlyId'
      preLoaderRoute: typeof ArticlePaperlyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper/$publicId': {
      id: '/paper/$publicId'
      path: '/paper/$publicId'
      fullPath: '/paper/$publicId'
      preLoaderRoute: typeof PaperPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify_/$certId': {
      id: '/verify_/$certId'
      path: '/verify/$certId'
      fullPath: '/verify/$certId'
      preLoaderRoute: typeof VerifyCertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-research/': {
      id: '/_authenticated/my-research/'
      path: '/my-research'
      fullPath: '/my-research/'
      preLoaderRoute: typeof AuthenticatedMyResearchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-research/$id': {
      id: '/_authenticated/my-research/$id'
      path: '/my-research/$id'
      fullPath: '/my-research/$id'
      preLoaderRoute: typeof AuthenticatedMyResearchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manuscript/$paperId': {
      id: '/_authenticated/manuscript/$paperId'
      path: '/manuscript/$paperId'
      fullPath: '/manuscript/$paperId'
      preLoaderRoute: typeof AuthenticatedManuscriptPaperIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcid/callback': {
      id: '/_authenticated/orcid/callback'
      path: '/orcid/callback'
      fullPath: '/orcid/callback'
      preLoaderRoute: typeof AuthenticatedOrcidCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify_/certificate/$certId': {
      id: '/verify_/certificate/$certId'
      path: '/verify/certificate/$certId'
      fullPath: '/verify/certificate/$certId'
      preLoaderRoute: typeof VerifyCertificateCertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/razorpay-webhook': {
      id: '/api/public/payments/razorpay-webhook'
      path: '/api/public/payments/razorpay-webhook'
      fullPath: '/api/public/payments/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedFounderRoute: typeof AuthenticatedFounderRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedMyResearchIdRoute: typeof AuthenticatedMyResearchIdRoute
  AuthenticatedManuscriptPaperIdRoute: typeof AuthenticatedManuscriptPaperIdRoute
  AuthenticatedOrcidCallbackRoute: typeof AuthenticatedOrcidCallbackRoute
  AuthenticatedMyResearchIndexRoute: typeof AuthenticatedMyResearchIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedFounderRoute: AuthenticatedFounderRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedMyResearchIdRoute: AuthenticatedMyResearchIdRoute,
  AuthenticatedManuscriptPaperIdRoute: AuthenticatedManuscriptPaperIdRoute,
  AuthenticatedOrcidCallbackRoute: AuthenticatedOrcidCallbackRoute,
  AuthenticatedMyResearchIndexRoute: AuthenticatedMyResearchIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  EditorialBoardRoute: EditorialBoardRoute,
  ExploreRoute: ExploreRoute,
  FeesRoute: FeesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  ArticlePaperlyIdRoute: ArticlePaperlyIdRoute,
  PaperPublicIdRoute: PaperPublicIdRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  VerifyCertIdRoute: VerifyCertIdRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
  VerifyCertificateCertIdRoute: VerifyCertificateCertIdRoute,
  ApiPublicPaymentsRazorpayWebhookRoute: ApiPublicPaymentsRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
