/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as PaperPublicIdRouteImport } from './routes/paper.$publicId'
import { Route as AuthenticatedMyResearchIndexRouteImport } from './routes/_authenticated/my-research.index'
import { Route as AuthenticatedMyResearchIdRouteImport } from './routes/_authenticated/my-research.$id'
import { Route as ApiPublicPaymentsRazorpayWebhookRouteImport } from './routes/api/public/payments/razorpay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PaperPublicIdRoute = PaperPublicIdRouteImport.update({
  id: '/paper/$publicId',
  path: '/paper/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyResearchIndexRoute =
  AuthenticatedMyResearchIndexRouteImport.update({
    id: '/my-research/',
    path: '/my-research/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyResearchIdRoute =
  AuthenticatedMyResearchIdRouteImport.update({
    id: '/my-research/$id',
    path: '/my-research/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsRazorpayWebhookRoute =
  ApiPublicPaymentsRazorpayWebhookRouteImport.update({
    id: '/api/public/payments/razorpay-webhook',
    path: '/api/public/payments/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/paper/$publicId': typeof PaperPublicIdRoute
  '/my-research/$id': typeof AuthenticatedMyResearchIdRoute
  '/my-research/': typeof AuthenticatedMyResearchIndexRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/paper/$publicId': typeof PaperPublicIdRoute
  '/my-research/$id': typeof AuthenticatedMyResearchIdRoute
  '/my-research': typeof AuthenticatedMyResearchIndexRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/paper/$publicId': typeof PaperPublicIdRoute
  '/_authenticated/my-research/$id': typeof AuthenticatedMyResearchIdRoute
  '/_authenticated/my-research/': typeof AuthenticatedMyResearchIndexRoute
  '/api/public/payments/razorpay-webhook': typeof ApiPublicPaymentsRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/verify'
    | '/admin'
    | '/certificates'
    | '/submit'
    | '/paper/$publicId'
    | '/my-research/$id'
    | '/my-research/'
    | '/api/public/payments/razorpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/verify'
    | '/admin'
    | '/certificates'
    | '/submit'
    | '/paper/$publicId'
    | '/my-research/$id'
    | '/my-research'
    | '/api/public/payments/razorpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/explore'
    | '/verify'
    | '/_authenticated/admin'
    | '/_authenticated/certificates'
    | '/_authenticated/submit'
    | '/paper/$publicId'
    | '/_authenticated/my-research/$id'
    | '/_authenticated/my-research/'
    | '/api/public/payments/razorpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  VerifyRoute: typeof VerifyRoute
  PaperPublicIdRoute: typeof PaperPublicIdRoute
  ApiPublicPaymentsRazorpayWebhookRoute: typeof ApiPublicPaymentsRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/paper/$publicId': {
      id: '/paper/$publicId'
      path: '/paper/$publicId'
      fullPath: '/paper/$publicId'
      preLoaderRoute: typeof PaperPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-research/': {
      id: '/_authenticated/my-research/'
      path: '/my-research'
      fullPath: '/my-research/'
      preLoaderRoute: typeof AuthenticatedMyResearchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-research/$id': {
      id: '/_authenticated/my-research/$id'
      path: '/my-research/$id'
      fullPath: '/my-research/$id'
      preLoaderRoute: typeof AuthenticatedMyResearchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/razorpay-webhook': {
      id: '/api/public/payments/razorpay-webhook'
      path: '/api/public/payments/razorpay-webhook'
      fullPath: '/api/public/payments/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedMyResearchIdRoute: typeof AuthenticatedMyResearchIdRoute
  AuthenticatedMyResearchIndexRoute: typeof AuthenticatedMyResearchIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedMyResearchIdRoute: AuthenticatedMyResearchIdRoute,
  AuthenticatedMyResearchIndexRoute: AuthenticatedMyResearchIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  VerifyRoute: VerifyRoute,
  PaperPublicIdRoute: PaperPublicIdRoute,
  ApiPublicPaymentsRazorpayWebhookRoute: ApiPublicPaymentsRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
